### ISSUE TITLE
Padrões para Wordpress

### ISSUE THREAD

**Issue by danielfsdo** [dindigital/style-patterns#4]
# Padronização WP
------------------------------
## Assets e dependências
Os assets e dependências devem ficar dentro de /src, assim como o NPM ou Yarn devem ser instalados lá dentro.

## Includes
Todos os modulos e includes devem ficar dentro de /includes.

## Functions
Todas as funçoes deve ser includes do functions.php presentes em /includes/functions e cada arquivo nomeado de acordo com as funções presentes nele. Ex.: ajax_load.php (funções referentes a carregamento ajax WP).
As funções que tratam de modificações no Painel WP, assim como criação de páginas administrativas devem ficar dentro de /function/admin.

## Querys
Para a estrutura de Query devemos: usar a wp_query em uma função localizada em /includes/functions/queries.php onde a função retorna a query montada.

## Versiomanto de assets:
Esse versionamento é feito com uma task do Gulp que gera um .json. Nesse arquivo estão as versões que precisam ser inseridas na chamada no functions. Abaixo a função que insere as versões e a task do Gulp.
```
	$version_file = file_get_contents(get_template_directory_uri().'/css/busters.json');
	$versions = json_decode($version_file, true);
	foreach ($versions as $key => $version) {
	    $key = str_replace('sass', 'css', $key);
	    $assetsVersion[$key] = $version;
	}

	function getVersionByKey($key)
	{
	    global $assetsVersion;
	    $key = "assets{$key}";
	    if (array_key_exists($key, $assetsVersion)) {
	        return $assetsVersion[$key];
	    }
	    return uniqid();
	}

	# - gulg:

	var bust = require('gulp-buster');

	gulp.task('version', function () {
	  return gulp.src([
	    'assets/sass/*.scss',
	    'assets/js/*.js'
	    ])

	    .pipe(bust())
	    .pipe(gulp.dest('../css'));
	});
```
## Cache
Cachear todas as funções que usam get_ de forma que o WP não busque mais no banco.
```
	- W3 Total Cache

	$social = wp_cache_get( 'homeA' );
	if ( false === $social ) {
	    // sem cache
	    $social = get_field('item');
	    wp_cache_set('homeA' , $social );
	}
	echo $social;
```

## YOAST SEO
- O menu Search Appearance do Yoast controla tudo que vai ser indexado. Nele é possível remover do sitemap os posts, páginas, taxonomias ou autor.

**Comment by nncl** [comment]
@danielfsdo acho que já seria legal criar a página na Wiki.

**Comment by kvnol** [comment]
@nncl iniciei a escrita da Wiki sobre WordPress: https://github.com/dindigital/style-patterns/wiki/Wordpress
